In [ ]:
import json
with open('intents_2.json','r') as f:
    data = json.load(f)

In [ ]:
from pandas import json_normalize 
d = json_normalize(data, 'intents')

In [ ]:
d.head()

           tag  ... context_set
0  [greetings]  ...         NaN
1        [bye]  ...         NaN
2    [creator]  ...         NaN
3        [age]  ...         NaN
4  [functions]  ...         NaN

[5 rows x 6 columns]

In [ ]:
df = d.assign(pattern=d.patterns.str.split(",")).explode('patterns')

In [ ]:
df.head()

           tag           patterns  ... context_set pattern
0  [greetings]                 Hi  ...         NaN     NaN
0  [greetings]        How are you  ...         NaN     NaN
0  [greetings]        How you are  ...         NaN     NaN
0  [greetings]  anyone Present Is  ...         NaN     NaN
0  [greetings]  anyone Is Present  ...         NaN     NaN

[5 rows x 7 columns]

In [ ]:
df['tags'] = df.tag.apply(lambda x: ', '.join([str(i) for i in x]))

In [ ]:
df.head()

           tag           patterns  ... pattern       tags
0  [greetings]                 Hi  ...     NaN  greetings
0  [greetings]        How are you  ...     NaN  greetings
0  [greetings]        How you are  ...     NaN  greetings
0  [greetings]  anyone Present Is  ...     NaN  greetings
0  [greetings]  anyone Is Present  ...     NaN  greetings

[5 rows x 8 columns]

In [ ]:
df.drop(['pattern'], axis=1)

                            tag  ... context_set
0                      greeting  ...
0                      greeting  ...
0                      greeting  ...
0                      greeting  ...
0                      greeting  ...
..                          ...  ...         ...
715              anger disorder  ...         NaN
716               anxiety anger  ...         NaN
717                    abruptly  ...         NaN
718             anger outbursts  ...         NaN
719  anger and bipolar disorder  ...         NaN

[3137 rows x 4 columns]

In [ ]:
df.to_csv('intent.csv')

In [ ]:
d.head()

In [ ]:
d = json_normalize(data,'intents')